"""Instrument reference-data lookup for the Trading Simulator.

Real trade-booking systems keep one master row per contract and have
every trade reference it, rather than each trade re-embedding its own
copy of the strike/expiry/exercise style -- this is the one place that
rule is enforced: every leg gets its Instrument through
`get_or_create_instrument`, never by constructing an `Instrument` row
directly.
"""
from __future__ import annotations

from datetime import date

from app.extensions import db
from app.models import Instrument


def occ_code(underlying_ticker: str, instrument_type: str, strike: float | None, expiry: date | None) -> str:
    """The standard OCC option symbol for this contract: root ticker,
    6-digit expiry (YYMMDD), C/P, and an 8-digit strike (strike*1000,
    zero-padded) -- e.g. AAPL270115C00300000 for a $300 call expiring
    2027-01-15. Stock has no strike/expiry, so its code is just the
    ticker. Deterministic and collision-free given this app's own
    uq_instrument_identity constraint, so it doubles as a lookup key."""
    ticker = underlying_ticker.upper()
    if instrument_type == "stock":
        return ticker
    side = "C" if instrument_type == "call" else "P"
    strike_field = f"{round(strike * 1000):08d}"
    return f"{ticker}{expiry.strftime('%y%m%d')}{side}{strike_field}"


def get_or_create_instrument(
    underlying_ticker: str,
    instrument_type: str,
    strike: float | None = None,
    expiry: date | None = None,
) -> Instrument:
    """Returns the existing Instrument for this exact contract if one's
    already been booked, otherwise creates it. US equity options are
    always American-style and physically settled -- there's no other
    kind in this app's data source (yfinance), so that's filled in here
    rather than asked of the caller."""
    if instrument_type not in ("stock", "call", "put"):
        raise ValueError(f"instrument_type must be 'stock', 'call', or 'put', got {instrument_type!r}")

    existing = Instrument.query.filter_by(
        underlying_ticker=underlying_ticker,
        instrument_type=instrument_type,
        strike=strike,
        expiry=expiry,
    ).first()
    if existing is not None:
        return existing

    is_option = instrument_type in ("call", "put")
    instrument = Instrument(
        underlying_ticker=underlying_ticker,
        instrument_type=instrument_type,
        strike=strike,
        expiry=expiry,
        exercise_style="american" if is_option else None,
        settlement_type="physical" if is_option else None,
        contract_multiplier=100 if is_option else 1,
        code=occ_code(underlying_ticker, instrument_type, strike, expiry),
    )
    db.session.add(instrument)
    db.session.flush()  # assigns instrument.id without a full commit, so the caller can attach a Leg to it in the same transaction
    return instrument


def find_instrument(code: str) -> Instrument | None:
    """Look up one instrument by its OCC-style code (case-insensitive --
    it's typed by a human, not generated by a machine)."""
    return Instrument.query.filter(db.func.upper(Instrument.code) == code.upper()).first()


def search_instruments(query: str | None) -> list[Instrument]:
    """Every instrument whose code or underlying ticker contains `query`
    (case-insensitive), newest first. Empty/absent query returns everything
    -- this catalog is small enough that "browse it all" is a real use case,
    not just a fallback."""
    q = Instrument.query
    if query:
        like = f"%{query.strip().upper()}%"
        q = q.filter(
            db.or_(
                db.func.upper(Instrument.code).like(like),
                db.func.upper(Instrument.underlying_ticker).like(like),
            )
        )
    return q.order_by(Instrument.id.desc()).limit(200).all()
