"""instrument codes and risk request scope

Revision ID: 2409b0483d54
Revises: 4a52c59eb3a2
Create Date: 2026-08-23 02:19:03.411892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2409b0483d54'
down_revision = '4a52c59eb3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # `code` is NOT NULL against a table that may already have rows, so it
    # can't be added NOT NULL directly (Postgres backfills NULL before
    # validating the constraint, and immediately fails it). Add it
    # nullable, backfill each row's real OCC code in Python (it varies per
    # row, so a single server_default can't do it), then tighten.
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=24), nullable=True))

    conn = op.get_bind()
    instruments = sa.table(
        'instruments',
        sa.column('id', sa.Integer),
        sa.column('underlying_ticker', sa.String),
        sa.column('instrument_type', sa.String),
        sa.column('strike', sa.Float),
        sa.column('expiry', sa.Date),
        sa.column('code', sa.String),
    )
    for row in conn.execute(sa.select(
        instruments.c.id, instruments.c.underlying_ticker, instruments.c.instrument_type,
        instruments.c.strike, instruments.c.expiry,
    )):
        if row.instrument_type == 'stock':
            code = row.underlying_ticker.upper()
        else:
            side = 'C' if row.instrument_type == 'call' else 'P'
            strike_field = f"{round(row.strike * 1000):08d}"
            code = f"{row.underlying_ticker.upper()}{row.expiry.strftime('%y%m%d')}{side}{strike_field}"
        conn.execute(instruments.update().where(instruments.c.id == row.id).values(code=code))

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('code', existing_type=sa.String(length=24), nullable=False)
        batch_op.create_index(batch_op.f('ix_instruments_code'), ['code'], unique=True)

    # `scope` is likewise NOT NULL against populated rows. Every existing
    # request predates book-level runs, so it's either 'leg' (leg_id set)
    # or 'position' (leg_id NULL, strategy_id set, from the earlier
    # position-level rollout) -- never 'book'.
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=8), nullable=True))
    op.execute(
        "UPDATE risk_requests SET scope = CASE WHEN leg_id IS NOT NULL THEN 'leg' ELSE 'position' END "
        "WHERE scope IS NULL"
    )
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.alter_column('scope', existing_type=sa.String(length=8), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
