"""add pipeline_runs.fast_mode

Revision ID: 42f08288966f
Revises: b7b8dfd54c9a
Create Date: 2026-08-22 22:04:01.283890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f08288966f'
down_revision = 'b7b8dfd54c9a'
branch_labels = None
depends_on = None


def upgrade():
    # server_default required: existing rows would otherwise fail the
    # NOT NULL constraint immediately (Postgres backfills them with NULL
    # before validating). Dropped again after backfill since the ORM
    # model always sets this explicitly going forward -- it's a
    # migration-time safety net, not meant to be the long-term default.
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fast_mode', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.alter_column('fast_mode', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_column('fast_mode')

    # ### end Alembic commands ###
