"""risk requests target a position

Revision ID: 4a52c59eb3a2
Revises: a452e7b14c7a
Create Date: 2026-08-23 01:31:21.704317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a52c59eb3a2'
down_revision = 'a452e7b14c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totals', sa.JSON(none_as_null=True), nullable=True))
        batch_op.alter_column('leg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_risk_requests_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_foreign_key(None, 'strategies', ['strategy_id'], ['id'])

    # Backfill: every existing request was run against a single leg, and
    # that leg belongs to a position. Without this they'd have a NULL
    # strategy_id and silently vanish from their own position's risk
    # history, which is the exact query this change exists to enable.
    op.execute(
        """
        UPDATE risk_requests
           SET strategy_id = legs.strategy_id
          FROM legs
         WHERE legs.id = risk_requests.leg_id
           AND risk_requests.strategy_id IS NULL
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_risk_requests_strategy_id'))
        batch_op.alter_column('leg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('totals')
        batch_op.drop_column('strategy_id')

    # ### end Alembic commands ###
