"""widen instrument code, add risk request error

Revision ID: 59fb3611371d
Revises: 2409b0483d54
Create Date: 2026-08-23 02:31:50.163177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fb3611371d'
down_revision = '2409b0483d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.drop_column('error')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###
