"""initial schema

Revision ID: a29fa3e84663
Revises: 
Create Date: 2026-08-22 04:18:20.510824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29fa3e84663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('appearance_id', sa.String(length=20), nullable=False),
    sa.Column('head_type_id', sa.String(length=20), nullable=False),
    sa.Column('body_type_id', sa.String(length=20), nullable=False),
    sa.Column('hand_type_id', sa.String(length=20), nullable=False),
    sa.Column('icebreaker_answer_food', sa.String(length=80), nullable=True),
    sa.Column('icebreaker_answer_movie', sa.String(length=80), nullable=True),
    sa.Column('icebreaker_answer_hobby', sa.String(length=80), nullable=True),
    sa.Column('icebreaker_answer_weekend', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('world_x', sa.Float(), nullable=True),
    sa.Column('world_y', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_status'), ['status'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_ticker', sa.String(length=10), nullable=False),
    sa.Column('instrument_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('exercise_style', sa.String(length=9), nullable=True),
    sa.Column('settlement_type', sa.String(length=8), nullable=True),
    sa.Column('contract_multiplier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying_ticker', 'instrument_type', 'strike', 'expiry', name='uq_instrument_identity')
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_underlying_ticker'), ['underlying_ticker'], unique=False)

    op.create_table('price_cache',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_session_id'), ['session_id'], unique=False)

    op.create_table('legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_iv', sa.Float(), nullable=True),
    sa.Column('entry_underlying_price', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legs_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_legs_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=4), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_character_id'), ['character_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_started_at'), ['started_at'], unique=False)

    op.create_table('risk_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('scenario', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_requests_leg_id'), ['leg_id'], unique=False)

    op.create_table('risk_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_request_id', sa.Integer(), nullable=False),
    sa.Column('leg_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('underlying_price_used', sa.Float(), nullable=False),
    sa.Column('pv', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('ir_delta', sa.Float(), nullable=True),
    sa.Column('scenario_gamma', sa.Float(), nullable=True),
    sa.Column('ir_vega', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['leg_id'], ['legs.id'], ),
    sa.ForeignKeyConstraint(['risk_request_id'], ['risk_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_results_leg_id'), ['leg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_results_risk_request_id'), ['risk_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_results_risk_request_id'))
        batch_op.drop_index(batch_op.f('ix_risk_results_leg_id'))

    op.drop_table('risk_results')
    with op.batch_alter_table('risk_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_requests_leg_id'))

    op.drop_table('risk_requests')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_character_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_legs_instrument_id'))

    op.drop_table('legs')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_session_id'))

    op.drop_table('strategies')
    op.drop_table('price_cache')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_underlying_ticker'))

    op.drop_table('instruments')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_status'))
        batch_op.drop_index(batch_op.f('ix_characters_session_id'))

    op.drop_table('characters')
    # ### end Alembic commands ###
