"""add timed_squares_scores

Revision ID: d153b8773f7a
Revises: 59fb3611371d
Create Date: 2026-08-23 05:09:45.085962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd153b8773f7a'
down_revision = '59fb3611371d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timed_squares_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_name', sa.String(length=12), nullable=False),
    sa.Column('turns_survived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timed_squares_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timed_squares_scores_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timed_squares_scores_turns_survived'), ['turns_survived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timed_squares_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timed_squares_scores_turns_survived'))
        batch_op.drop_index(batch_op.f('ix_timed_squares_scores_session_id'))

    op.drop_table('timed_squares_scores')
    # ### end Alembic commands ###
