"""Add job_listings and job_search_profiles for Job Discovery

Revision ID: ec8d3b5da35f
Revises: d3a1f7c05e92
Create Date: 2026-09-13 15:00:00.000000

Hand-written rather than autogenerated: `flask db migrate` on this repo's
dev DB also picked up pre-existing, unrelated model/schema drift on
characters/instruments/pipeline_runs/risk_requests (present before this
change) that does not belong in a Job Discovery migration.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8d3b5da35f'
down_revision = 'd3a1f7c05e92'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'job_listings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.Text(), nullable=False),
        sa.Column('role_title', sa.Text(), nullable=False),
        sa.Column('location', sa.Text(), nullable=True),
        sa.Column('job_posting_url', sa.Text(), nullable=False),
        sa.Column('date_posted', sa.Date(), nullable=True),
        sa.Column('salary_range', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('source', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('match_grade', sa.Integer(), nullable=True),
        sa.Column('match_notes', sa.Text(), nullable=True),
        sa.Column('promoted_application_id', sa.Integer(), nullable=True),
        sa.Column('found_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['promoted_application_id'], ['job_applications.id'], ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_job_listings_job_posting_url'), ['job_posting_url'], unique=False
        )

    op.create_table(
        'job_search_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('keywords', sa.Text(), nullable=False),
        sa.Column('location', sa.Text(), nullable=True),
        sa.Column('remote_only', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )


def downgrade():
    op.drop_table('job_search_profiles')
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_listings_job_posting_url'))
    op.drop_table('job_listings')
