"""add users and leetcode_progress

Accounts for the LeetCode 150 tracker (each account keeps its own board).
Hand-written rather than autogenerated: the two tables are plain creates,
and running the full migration chain against SQLite for autogenerate trips
an unrelated pre-existing batch-op issue. Constraints are named explicitly
so this applies cleanly on both Postgres (prod) and SQLite.

Revision ID: f4e9c2a7b810
Revises: c1d4e7a9b230
Create Date: 2026-08-28 01:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e9c2a7b810'
down_revision = 'c1d4e7a9b230'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=32), nullable=False),
        sa.Column('username_ci', sa.String(length=32), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_users'),
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username_ci', ['username_ci'], unique=True)

    op.create_table(
        'leetcode_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('slug', sa.String(length=80), nullable=False),
        sa.Column('mark', sa.String(length=3), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name='fk_leetcode_progress_user_id_users'
        ),
        sa.PrimaryKeyConstraint('id', name='pk_leetcode_progress'),
        sa.UniqueConstraint('user_id', 'slug', name='uq_leetcode_progress_user_slug'),
    )
    with op.batch_alter_table('leetcode_progress', schema=None) as batch_op:
        batch_op.create_index(
            'ix_leetcode_progress_user_id', ['user_id'], unique=False
        )


def downgrade():
    with op.batch_alter_table('leetcode_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_leetcode_progress_user_id')
    op.drop_table('leetcode_progress')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username_ci')
    op.drop_table('users')
